# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myChat

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'SwiftKeychainWrapper'
  
  target 'myChatTest' do
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'SwiftKeychainWrapper'
    end

end
